# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- AngularProject

pool:
  vmImage: self_hosted_machine

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

