# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- AngularProject

pool:
  vmImage: 'ubuntu-latest'
  
  
steps:

- script: |
    npm install -g @angular/cli
    npm install
    ng build 
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/my-first-project/browser'

    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(922edf91-4682-4606-acea-276d71b86717)'
    appType: 'webAppLinux'
    WebAppName: 'agwbapp1'
    deployToSlotOrASE: true
    ResourceGroupName: 'web-app-resource-group'
    SlotName: 'qa-webapp'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|18-lts'
    StartupCommand: 'pm2 serve /home/site/wwwroot --no-daemon'
