name: Angular Deployment

on:
  push:
    branches:
      - AngularProject

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.4.0
        with:
          aws-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          source-dir: dist/my-first-project
          dest-bucket: 331952164793-fastccinboxnxnew-parameterservice-dev-origin

      - name: CloudFront Invalidation
        uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
        with:
          cloudfront-distribution-id: E3I8YYIJ90V9BM
          paths: '/*'
